spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-3-231-16-122.compute-1.amazonaws.com:5432/deja68kial2anh?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: ysvvaqkxbwomvk
    password: 7b38ddb020eb68c0fb4a6096526abf18acf0f1d461f79884c1c002b087754a92
